version: '3.8'
services:
  pfb_database:
    image: postgres:13
    container_name: pfb_database
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_INITDB_ARGS=--data-checksums --auth-local=peer --auth-host=md5
    ports:
      - '15001:5432'